name: Run Testing Environment

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run on"
        required: false
        default: "dev-candidate"
        type: string

jobs:
  Run-Test-Cases:
    runs-on: ubuntu-latest
    env:
      LARGE_SECRET_PASSPHRASE: ${{ secrets.TESTING_PHRASE }}

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install required Linux packages
        run: |
          sudo apt-get update && sudo apt-get install -y git gnupg

      - name: Clone target repo
        run: |
          git clone -b ${{ github.event.inputs.branch }} --single-branch https://github.com/I-GUIDE/iguide-ue-backend.git

      - name: Install npm packages
        working-directory: iguide-ue-backend
        run: |
          npm install

      - name: Decrypt secrets
        working-directory: iguide-ue-backend/tests/secrets
        run: |
          sh decrypt.sh

      - name: Run tests
        working-directory: iguide-ue-backend
        run: |
          npm run test:dev
