name: Run Testing Environment

on:
  workflow_dispatch:  # Allows manual triggering
    inputs:
      branch:
        description: "Branch to run on"
        required: false
        default: "main"  # Default branch
        type: string

jobs:
  setup-test-env:
    runs-on: ubuntu-latest
    env:
      # Example of setting an environment variable
      LARGE_SECRET_PASSPHRASE: ${{ secrets.TESTING_PHRASE }}
    
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install required Linux packages
        run: |
          sudo apk --no-cache add git gpg gpg-agent || sudo apt-get update && sudo apt-get install -y git gnupg

      - name: Clone target repo
        run: |
          git clone -b dev-candidate --single-branch https://github.com/I-GUIDE/iguide-ue-backend.git
          cd iguide-ue-backend
          npm install

      - name: Decrypt secrets
        run: |
          cd iguide-ue-backend/tests/secrets
          sh decrypt.sh

      - name: Run tests
        run: |
          pwd
          cd ../../
          cd iguide-ue-backend
          pwd
          npm run test:dev
